trailingComma: 'none'
bracketSameLine: false
tabWidth: 2
semi: true
singleQuote: true
plugins: ['prettier-plugin-svelte']
pluginSearchDirs: ['.']
overrides: [{ 'files': '*.svelte', 'options': { 'parser': 'svelte' } }]
