trailingComma: "none"
bracketSameLine: false
tabWidth: 2
semi: true
singleQuote: false
plugins: ["prettier-plugin-svelte"]
pluginSearchDirs: ["."]
overrides: [{ "files": "*.svelte", "options": { "parser": "svelte" } }]
